In [1]:
import numpy as np

In [12]:
a=np.array([])

In [3]:
type(a)

numpy.ndarray

In [13]:
b=np.array([1,2,3,4,5,6])

In [5]:
b

array([1, 2, 3, 4, 5, 6])

In [6]:
print(b)

[1 2 3 4 5 6]


In [7]:
type(b)

numpy.ndarray

In [8]:
b.size

6

In [9]:
b.shape

(6,)

In [10]:
#(row,column)

In [11]:
b.ndim

1

In [12]:
b.dtype

dtype('int32')

In [13]:
len(b)

6

In [14]:
# 2d array

In [15]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
c.ndim

2

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
c.shape

(3, 3)

In [22]:
c.size

9

In [4]:
#3d array
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
e=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[4,5,6],[7,8,9],[1,2,3]],[[7,8,9],[1,2,3],[4,5,6]]])

In [7]:
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]],

       [[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]]])

In [8]:
e.ndim

3

In [9]:
e.shape

(3, 3, 3)

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
c[0,0] #c[row,column]

1

In [19]:
c[0]

array([1, 2, 3])

In [21]:
c[:,2] #for column

array([3, 6, 9])

In [22]:
c[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [23]:
c[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [24]:
e

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9],
        [1, 2, 3]],

       [[7, 8, 9],
        [1, 2, 3],
        [4, 5, 6]]])

In [25]:
# [row,column,plane]

In [26]:
s=np.eye(5)

In [27]:
s

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
x=np.ones((5,5))

In [29]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
v=np.zeros(10)

In [31]:
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.empty((4,4))

array([[9.03460939e-308, 2.24185092e-303, 1.03797958e-305,
        5.25386874e-306],
       [3.05093697e-306, 3.05093697e-306, 3.05093697e-306,
        3.05093697e-306],
       [3.06742946e-306, 2.24185092e-303, 2.24185092e-303,
        2.24185092e-303],
       [5.44247185e-292, 4.06286756e-306, 3.87858191e-306,
        9.77654871e-306]])

In [33]:
b.dtype

dtype('int32')

In [34]:
#arrange
#reshape
#random

In [35]:
a=range(0,10)

In [36]:
a=list(a)

In [37]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
list(range(2.5,10.2))

<class 'TypeError'>: 'float' object cannot be interpreted as an integer

In [42]:
np.arange(2.5,10.5)

array([2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [43]:
np.arange(-10,0)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [45]:
np.arange(-8.5,1)

array([-8.5, -7.5, -6.5, -5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5])

In [46]:
b=np.array([1,2,3,4,5,6])

In [47]:
b

array([1, 2, 3, 4, 5, 6])

In [48]:
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
b.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [52]:
np.arange(16).reshape(1,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [53]:
#unkonwn reshape
np.arange(12).reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
#RANDOM
np.random.rand(5)

array([0.7805386 , 0.61491039, 0.3337251 , 0.83603963, 0.93777092])

In [55]:
np.random.rand(2,2)

array([[0.31696476, 0.79828041],
       [0.0142388 , 0.38530833]])

In [58]:
np.random.randint(5,9,2)

array([5, 7])

In [59]:
f=np.random.randint(5,9,2)

In [60]:
f.reshape(2,1)

array([[7],
       [6]])

In [61]:
np.argmax(a) #Argmax,Argmin
#np.nan
#Calculation

9

In [62]:
np.argmin(a)

0

In [64]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [65]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.argmax(a)

8

In [67]:
np.argmin(a)

0

In [68]:
a=np.array([[1,np.nan],[np.nan,4]])

In [69]:
a

array([[ 1., nan],
       [nan,  4.]])

In [70]:
a=np.array([5,6,7,8,9])

In [71]:
a.mean()

7.0

In [72]:
a.max()

9

In [74]:
a.min()

5

In [75]:
a*2

array([10, 12, 14, 16, 18])

In [76]:
1/a

array([0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [77]:
a+a

array([10, 12, 14, 16, 18])

In [78]:
a*a

array([25, 36, 49, 64, 81])

In [79]:
np.sum(a)

35

In [80]:
np.sqrt(a)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [81]:
a=np.array([[5,6,7],[8,9,0],[1,2,3]])

In [82]:
a

array([[5, 6, 7],
       [8, 9, 0],
       [1, 2, 3]])

In [83]:
np.ravel(a)

array([5, 6, 7, 8, 9, 0, 1, 2, 3])

In [9]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [10]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [14]:
a=np.linspace(1,100,10)

In [15]:
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
np.power(2,3)

8